"""Databse creation

Revision ID: 54256ef9c928
Revises: 
Create Date: 2023-03-11 00:01:43.277494

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '54256ef9c928'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('solution', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('number', sa.Integer(), nullable=False),
                    sa.Column('difficulty', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('theme',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('intersection',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('task_id', sa.Integer(), nullable=True),
                    sa.Column('theme_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
                    sa.ForeignKeyConstraint(['theme_id'], ['theme.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('intersection')
    op.drop_table('theme')
    op.drop_table('task')
    # ### end Alembic commands ###
